version: '3.8'

services:
  iims-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iims-ai-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONPATH=/app
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount artifacts directory for model persistence
      - ./artifacts:/app/artifacts
      # Optional: Mount source for development (comment out for production)
      # - ./src:/app/src
    restart: unless-stopped
    networks:
      - iims-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  iims-ai-network:
    driver: bridge
